version: "1.0"
project:
  name: bodywork-pipeline-with-mlflow
  docker_image: bodyworkml/bodywork-core:latest
  DAG: train_model >> scoring_service
stages:
  train_model:
    executable_module_path: train_model.py
    requirements:
      - mlflow==1.17.0
      - numpy==1.19.4
      - pandas==1.1.4
      - scikit-learn==0.23.2
    cpu_request: 0.5
    memory_request_mb: 100
    batch:
      max_completion_time_seconds: 30
      retries: 2
  scoring_service:
    executable_module_path: serve_model.py
    requirements:
      - Flask==1.1.2
      - mlflow==1.17.0
      - numpy==1.19.4
      - scikit-learn==0.23.2
    cpu_request: 0.25
    memory_request_mb: 100
    service:
      max_startup_time_seconds: 30
      replicas: 2
      port: 5000
      ingress: true
logging:
  log_level: INFO
